---
title: "Environmental Data Science Summit 2022"
description: |
  February 8-9, 2022 | Santa Barbara, California
site: distill::distill_website
includes:
      in_header: assets/header.html
      after_body: assets/_footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
## Building a broad tent for environmental data science.

Our inaugural summit will focus on **Harnessing Diversity in Environmental Data Science.**


Environmental Data Science (EDS) is a growing field of interdisciplinary approaches to answer environmental questions by using modern data science tools to discover and synthesize large amounts of data. This field is broad, diverse, and expanding. Our goal is to bring together all types of environmental data scientists to begin laying the foundation for a more cohesive and collaborative EDS community that reaches beyond disciplinary boundaries. 

### If you use data to ask questions about our environment and how we interact with it, this summit is for you! 


-----

More details to come. If you'd like to be the first to know sign up for our mailing list below

[Click here to join the mailing list](https://ye3xql7qgkg.typeform.com/to/PKN2wSp6)


----
### Steering committee 

Do we want to list the steering committee?


Add footer with NCEAS logo

