---
title: "Participation & Application"
output:
  distill::distill_article:
editor_options: 
  chunk_output_type: console
---

## Participation & Application

Participation is limited to 100 attendees, with an application required. We are able to provide funding for up to 60 participants. Funding will cover travel to Santa Barbara, lodging, and the Summit registration fee. In order to attend you must first apply. Applications will be used both to select participation and award funding.

Participant attendance is not limited by sector, discipline, background, or career stage. If you use data to ask questions about our environment and how we interact with it, this Summit is for you! 

A detailed agenda will be shared with participants closer to the Summit. We are monitoring the global COVID-19 pandemic situation and will alter the format of the Summit as necessary, given state and local guidance. As of August 2022, we are planning for an in-person event.

Applications open on August 10th and will close on October 1st. Selected participants will be notified by October 31st.

**Applications have closed.**
